# Usa una base immagine ufficiale di Python
FROM python:3.12-slim

# Imposta la directory di lavoro nel container
WORKDIR /app

# Copia la cartella src nel container
COPY src /app

# Copia requirements.txt nella cartella di lavoro
COPY requirements.txt /app/

# Installa le dipendenze
RUN pip install --no-cache-dir -r /app/requirements.txt

# Imposta il comando per avviare l'applicazione
CMD ["python", "app.py"]
